language: python

services:
  - docker

env:
  - DOCKER_IMAGE=pangeo/pangeo-ocean:2019.03.12
  - DOCKER_IMAGE=pangeo/pangeo-notebook

before_install:
- docker pull $DOCKER_IMAGE
- docker run -d --name pangeo $DOCKER_IMAGE
- docker cp . pangeo:/home/jovyan/
- docker ps -a
- docker exec pangeo bash -c "pip install pytest"

script:
- docker exec pangeo env TERM=xterm script bash -c " py.test --durations=9999 -v tests/validate_datasets.py"
