language: python

services:
  - docker

env:
  - DOCKER_IMAGE=pangeo/pangeo-notebook:2019.04.19

before_install:
- docker pull $DOCKER_IMAGE
- docker run -d --name pangeo $DOCKER_IMAGE
- docker exec pangeo bash -c "pip install pytest"
- docker ps -a

install:
- docker cp . pangeo:/home/jovyan/

script:
- >
   docker exec -it pangeo bash -c
   'py.test --durations=9999 -v tests/*.py'
