language: python

services:
  - docker

env:
  - DOCKER_IMAGE=pangeo/pangeo-notebook:2019.04.19

before_install:
- docker pull $DOCKER_IMAGE
- docker run -d -it --name pangeo -p 8888:8888 $DOCKER_IMAGE jupyter notebook --ip 0.0.0.0 --allow-root
- docker ps -a
- docker exec pangeo bash -c "pip install pytest"

install:
- docker cp . pangeo:/home/jovyan/

script:
- >
   docker exec -it pangeo bash -c
   'py.test --durations=9999 -v tests/*.py'
